namespace Lifecycle.Core.Contracts;

/// <summary>A durable department handoff notification generated by the automation worker.</summary>
public sealed record NotificationResponse(
    long Id,
    Guid CustomerId,
    string CustomerName,
    string TargetDepartment,
    string Message,
    DateTimeOffset CreatedAt,
    DateTimeOffset? ReadAt);
